openapi: 3.0.0
info:
  title: DataFed System API
  description: DataFed system API for production and custom clients
  version: 2.0.0
servers:
  #- url: https://datafed.ornl.gov/v2
  #  description: DataFed production API Gateway Server
  - url: https://sdms.ornl.gov:50100/v2
    description: DataFed development API Gateway Server
  - url: http://localhost/v2
    description: Local Development API Gateway Server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    access_rule:
      $ref: "components/schemas/access_rule.yaml"
    allocation:
      $ref: "components/schemas/allocation.yaml"
    annotation:
      $ref: "components/schemas/annotation.yaml#/annotation"
    category:
      $ref: "components/schemas/category.yaml"
    relationship:
      $ref: "components/schemas/relationship.yaml"
    folder:
      $ref: "components/schemas/folder.yaml#/folder"
    group:
      $ref: "components/schemas/group.yaml"
    project:
      $ref: "components/schemas/project.yaml"
    record:
      $ref: "components/schemas/record.yaml#/record"
    repository:
      $ref: "components/schemas/repo.yaml"
    schema:
      $ref: "components/schemas/schema.yaml"
    search_criteria:
      $ref: "components/schemas/search_criteria.yaml"
    search_saved:
      $ref: "components/schemas/search_saved.yaml"
    search_specification:
      $ref: "components/schemas/search_specification.yaml"
    task:
      $ref: "components/schemas/task.yaml"
    token_grant:
      $ref: "components/schemas/token_grant.yaml"
    user:
      $ref: "components/schemas/user.yaml"
security:
  - bearerAuth: [] # Default auth is JWT bearer token
paths:
  /version:
    get:
      description: Get full DataFed system version.
      tags:
        - general
      security: [] # No auth required for this method
      responses:
        '200':
          description: System version as a JSON document
          content:
            application/json:
              schema:
                type: object
                properties:
                  major:
                    type: integer
                    minimum: 0
                    description: Major version number
                  minor:
                    type: integer
                    minimum: 0
                    description: Minor version number
                  build:
                    type: integer
                    minimum: 0
                    description: Build number

  # ========== Authentication Endpoints ==========

  # ---- Anonymous Endpoints ----

  /authn/basic:
    $ref: "paths/authn.yaml#/basic"
  /authn/token/exchange:
    $ref: "paths/authn.yaml#/token_exchange"

  # ---- Authenticated Endpoints ----

  /api/authn/logout:
    $ref: "paths/authn.yaml#/logout"
  /api/authn/token_revoke:
    $ref: "paths/authn.yaml#/token_revoke"

  # ========== User Endpoints ==========

  /api/user/who:
    $ref: "paths/user.yaml#/who"
  /api/user/list/all:
    $ref: "paths/user.yaml#/list_all"
  /api/user/list/collab:
    $ref: "paths/user.yaml#/list_collab"
  /api/user/find:
    $ref: "paths/user.yaml#/find"
  /api/user/view:
    $ref: "paths/user.yaml#/view"

  # ========== Project Endpoints ==========

  /api/project/list:
    $ref: "paths/project.yaml#/list"
  /api/project/find:
    $ref: "paths/project.yaml#/find"
  /api/project/create:
    $ref: "paths/project.yaml#/create"
  /api/project/view:
    $ref: "paths/project.yaml#/view"
  /api/project/update:
    $ref: "paths/project.yaml#/update"
  /api/project/update/members:
    $ref: "paths/project.yaml#/update_members"
  /api/project/update/admins:
    $ref: "paths/project.yaml#/update_admins"
  /api/project/delete:
    $ref: "paths/project.yaml#/delete"

  # ========== Group Endpoints ==========

  /api/group/list:
    $ref: "paths/group.yaml#/list"
  /api/group/create:
    $ref: "paths/group.yaml#/create"
  /api/group/view:
    $ref: "paths/group.yaml#/view"
  /api/group/update:
    $ref: "paths/group.yaml#/update"
  /api/group/delete:
    $ref: "paths/group.yaml#/delete"

  # ========== Folder Endpoints ==========

  /api/folder/create:
    $ref: "paths/folder.yaml#/create"
  /api/folder/view:
    $ref: "paths/folder.yaml#/view"
  /api/folder/update:
    $ref: "paths/folder.yaml#/update"
  /api/folder/delete:
    $ref: "paths/folder.yaml#/delete"
  /api/folder/items/list:
    $ref: "paths/folder.yaml#/items_list"
  /api/folder/items/link:
    $ref: "paths/folder.yaml#/items_link"
  /api/folder/items/unlink:
    $ref: "paths/folder.yaml#/items_unlink"
  /api/folder/items/move:
    $ref: "paths/folder.yaml#/items_move"
  /api/folder/items/lock:
    $ref: "paths/folder.yaml#/items_lock"
  /api/folder/items/unlock:
    $ref: "paths/folder.yaml#/items_unlock"

  # ========== Data Record Endpoints ==========

  /api/record/create:
    $ref: "paths/record.yaml#/create"
  /api/record/view:
    $ref: "paths/record.yaml#/view"
  /api/record/update:
    $ref: "paths/record.yaml#/update"
  /api/record/update/allocation:
    $ref: "paths/record.yaml#/update_allocation"
  /api/record/update/owner:
    $ref: "paths/record.yaml#/update_owner"
  /api/record/delete:
    $ref: "paths/record.yaml#/delete"
  /api/record/lock:
    $ref: "paths/record.yaml#/lock"
  /api/record/unlock:
    $ref: "paths/record.yaml#/unlock"
  /api/record/import:
    $ref: "paths/record.yaml#/import"
  /api/record/export:
    $ref: "paths/record.yaml#/export"
  /api/record/provenance/graph:
    $ref: "paths/record.yaml#/prov_graph"
  /api/record/metadata/validate:
    $ref: "paths/record.yaml#/metadata_validate"
  /api/record/data/download:
    $ref: "paths/record.yaml#/data_download"
  /api/record/data/upload:
    $ref: "paths/record.yaml#/data_upload"
  /api/record/data/delete:
    $ref: "paths/record.yaml#/data_delete"

  # ========== Annotations Endpoints ==========

  /api/annotate/list:
    $ref: "paths/annotate.yaml#/list"
  /api/annotate/create:
    $ref: "paths/annotate.yaml#/create"
  /api/annotate/view:
    $ref: "paths/annotate.yaml#/view"
  /api/annotate/update:
    $ref: "paths/annotate.yaml#/update"
  /api/annotate/comment:
    $ref: "paths/annotate.yaml#/comment"
  /api/annotate/comment/edit:
    $ref: "paths/annotate.yaml#/comment_edit"

  # ========== Access Control Endpoints ==========

  /api/access/permissions/verify:
    $ref: "paths/access.yaml#/perm_verify"
  /api/access/permissions/get:
    $ref: "paths/access.yaml#/perm_get"
  /api/access/rules/view:
    $ref: "paths/access.yaml#/rules_view"
  /api/access/rules/set:
    $ref: "paths/access.yaml#/rules_set"
  /api/access/rules/add:
    $ref: "paths/access.yaml#/rules_add"
  /api/access/rules/remove:
    $ref: "paths/access.yaml#/rules_remove"

  # ========== Data Sharing Endpoints ==========

  /api/shares/accounts/list:
    $ref: "paths/shares.yaml#/accounts_list"
  /api/shares/items/list:
    $ref: "paths/shares.yaml#/items_list"

  # ========== Schema Endpoints ==========

  /api/schema/list:
    $ref: "paths/schema.yaml#/list"
  /api/schema/find:
    $ref: "paths/schema.yaml#/find"
  /api/schema/create:
    $ref: "paths/schema.yaml#/create"
  /api/schema/view:
    $ref: "paths/schema.yaml#/view"
  /api/schema/update:
    $ref: "paths/schema.yaml#/update"
  /api/schema/revise:
    $ref: "paths/schema.yaml#/revise"
  /api/schema/delete:
    $ref: "paths/schema.yaml#/delete"

  # ========== Repository Endpoints ==========

  /api/repo/list:
    $ref: "paths/repo.yaml#/list"
  /api/repo/view:
    $ref: "paths/repo.yaml#/view"
  /api/repo/create:
    $ref: "paths/repo.yaml#/create"
  /api/repo/update:
    $ref: "paths/repo.yaml#/update"
  /api/repo/delete:
    $ref: "paths/repo.yaml#/delete"
  /api/repo/statistics:
    $ref: "paths/repo.yaml#/statistics"
  /api/repo/alloc/list:
    $ref: "paths/repo.yaml#/alloc_list"

  # ========== Allocation Endpoints ==========

  # ----- User Role -----

  /api/alloc/list:
    $ref: "paths/alloc.yaml#/list"
  /api/alloc/view:
    $ref: "paths/alloc.yaml#/view"
  /api/alloc/default/get:
    $ref: "paths/alloc.yaml#/default_get"
  /api/alloc/default/set:
    $ref: "paths/alloc.yaml#/default_set"
  /api/alloc/records/list:
    $ref: "paths/alloc.yaml#/records_list"
  /api/alloc/statistics:
    $ref: "paths/alloc.yaml#/statistics"

  # ----- Repo Admin Role -----

  /api/alloc/create:
    $ref: "paths/alloc.yaml#/create"
  /api/alloc/update:
    $ref: "paths/alloc.yaml#/update"
  /api/alloc/delete:
    $ref: "paths/alloc.yaml#/delete"

  # ========== Search Endpoints ==========

  /api/search/run:
    $ref: "paths/search.yaml#/run"
  /api/search/save:
    $ref: "paths/search.yaml#/save"
  /api/search/saved/list:
    $ref: "paths/search.yaml#/saved_list"
  /api/search/saved/run:
    $ref: "paths/search.yaml#/saved_run"
  /api/search/saved/view:
    $ref: "paths/search.yaml#/saved_view"
  /api/search/saved/update:
    $ref: "paths/search.yaml#/saved_update"
  /api/search/saved/delete:
    $ref: "paths/search.yaml#/saved_delete"

  # ========== Globus Endpoints ==========

  /api/globus/ep/recent/list:
    $ref: "paths/globus.yaml#/ep_recent_list"
  /api/globus/ep/favorite/list:
    $ref: "paths/globus.yaml#/ep_favorite_list"
  /api/globus/ep/favorite/add:
    $ref: "paths/globus.yaml#/ep_favorite_add"
  /api/globus/ep/favorite/remove:
    $ref: "paths/globus.yaml#/ep_favorite_remove"
  /api/globus/authz/verify:
    $ref: "paths/globus.yaml#/authz_verify"

  # ========== Catalog Endpoints ==========

  /api/catalog/category/list:
    $ref: "paths/catalog.yaml#/category_list"
  /api/catalog/category/search:
    $ref: "paths/catalog.yaml#/category_search"
  /api/catalog/category/view:
    $ref: "paths/catalog.yaml#/category_view"

  # ========== Task Endpoints ==========

  /api/task/list:
    $ref: "paths/task.yaml#/list"
  /api/task/view:
    $ref: "paths/task.yaml#/view"
  /api/task/cancel:
    $ref: "paths/task.yaml#/cancel"


  # ========== System Endpoints ==========

  # TBD
