openapi: 3.0.0
info:
  title: DataFed System API
  description: DataFed system API for production and custom clients
  version: 2.0.0
servers:
#  - url: https://datafed.ornl.gov/v2
#    description: DataFed Production API Gateway Server
  - url: http://localhost/v2
    description: Local Development API Gateway Server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    token_grant:
      $ref: "components/schemas/token_grant.yaml"
    user:
      $ref: "components/schemas/user.yaml"
    project:
      $ref: "components/schemas/project.yaml"
    group:
      $ref: "components/schemas/group.yaml"
    record:
      $ref: "components/schemas/record.yaml"
    folder:
      $ref: "components/schemas/folder.yaml"
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
security:
  - bearerAuth: [] # Default auth is JWT bearer token
paths:
  /version:
    get:
      description: Get full DataFed system version.
      tags:
        - general
      security: [] # No auth required for this method
      responses:
        '200':
          description: System version as a JSON document
          content:
            application/json:
              schema:
                type: object
                properties:
                  major:
                    type: integer
                    minimum: 0
                    description: Major version number
                  minor:
                    type: integer
                    minimum: 0
                    description: Minor version number
                  build:
                    type: integer
                    minimum: 0
                    description: Build number

  # ========== Authentication Endpoints ==========

  # ---- Anonymous Endpoints ----

  /authn/basic:
    $ref: "paths/authn.yaml#/basic"
  /authn/token/exchange:
    $ref: "paths/authn.yaml#/token_exchange"

  # ---- Authenticated Endpoints ----

  /api/authn/logout:
    $ref: "paths/authn.yaml#/logout"
  /api/authn/token_revoke:
    $ref: "paths/authn.yaml#/token_revoke"

  # ========== User Endpoints ==========

  /api/user/who:
    $ref: "paths/user.yaml#/who"
  /api/user/list/all:
    $ref: "paths/user.yaml#/list_all"
  /api/user/list/collab:
    $ref: "paths/user.yaml#/list_collab"
  /api/user/find:
    $ref: "paths/user.yaml#/find"
  /api/user/view:
    $ref: "paths/user.yaml#/view"

  # ========== Project Endpoints ==========

  /api/project/list:
    $ref: "paths/project.yaml#/list"
  /api/project/create:
    $ref: "paths/project.yaml#/create"
  /api/project/view:
    $ref: "paths/project.yaml#/view"
  /api/project/update:
    $ref: "paths/project.yaml#/update"
  /api/project/update/members:
    $ref: "paths/project.yaml#/update_members"
  /api/project/update/admins:
    $ref: "paths/project.yaml#/update_admins"
  /api/project/delete:
    $ref: "paths/project.yaml#/delete"

  # ========== Group Endpoints ==========

  /api/group/list:
    $ref: "paths/group.yaml#/list"
  /api/group/create:
    $ref: "paths/group.yaml#/create"
  /api/group/view:
    $ref: "paths/group.yaml#/view"
  /api/group/update:
    $ref: "paths/group.yaml#/update"
  /api/group/delete:
    $ref: "paths/group.yaml#/delete"

  # ========== Folder Endpoints ==========

  /api/folder/create:
    $ref: "paths/folder.yaml#/create"
  /api/folder/view:
    $ref: "paths/folder.yaml#/view"
  /api/folder/update:
    $ref: "paths/folder.yaml#/update"
  /api/folder/delete:
    $ref: "paths/folder.yaml#/delete"
  /api/folder/items/list:
    $ref: "paths/folder.yaml#/items_list"
  /api/folder/items/link:
    $ref: "paths/folder.yaml#/items_link"
  /api/folder/items/unlink:
    $ref: "paths/folder.yaml#/items_unlink"
  /api/folder/items/move:
    $ref: "paths/folder.yaml#/items_move"
  /api/folder/items/lock:
    $ref: "paths/folder.yaml#/items_lock"
  /api/folder/items/unlock:
    $ref: "paths/folder.yaml#/items_unlock"
