openapi: 3.0.0
info:
  title: DataFed System API
  description: DataFed system API for production and custom clients
  version: 2.0.0
servers:
#  - url: https://datafed.ornl.gov/v2
#    description: DataFed Production API Gateway Server
  - url: http://localhost/v2
    description: Local Development API Gateway Server
components:
  schemas:
    token_grant:
      $ref: "components/schemas/token_grant.yaml"
    user:
      $ref: "components/schemas/user.yaml"
    project:
      $ref: "components/schemas/project.yaml"
paths:
  /version:
    get:
      description: Get full DataFed system version.
      tags:
        - general
      responses:
        '200':
          description: System version as a JSON document
          content:
            application/json:
              schema:
                type: object
                properties:
                  major:
                    type: integer
                    minimum: 0
                    description: Major version number
                  minor:
                    type: integer
                    minimum: 0
                    description: Minor version number
                  build:
                    type: integer
                    minimum: 0
                    description: Build number

  /auth/basic:
    $ref: "paths/auth.yaml#/basic"

  /auth/token/exchange:
    $ref: "paths/auth.yaml#/token_exchange"

  /api/user/who:
    $ref: "paths/user.yaml#/who"
  /api/user/list:
    $ref: "paths/user.yaml#/list"
  /api/user/view:
    $ref: "paths/user.yaml#/view"

  /api/project/list:
    $ref: "paths/project.yaml#/list"
  /api/project/view:
    $ref: "paths/project.yaml#/view"
  /api/project/create:
    $ref: "paths/project.yaml#/create"
  /api/project/update:
    $ref: "paths/project.yaml#/update"
  /api/project/delete:
    $ref: "paths/project.yaml#/delete"
